name: configserver

applabels: configserver
#=====================
# DEPLOYMENT
#=====================

image:
  name: configserver-container
  repository: config-server
  tag: "02"
  port: 120
# cmt
resources:
  enabled: false
  # request:
  #   memory: 64Mi
  #   cpu: 250m
  # limit:
  #   memory: 128Mi
  #   cpu: 500m

#======================
# SERVICE
#=====================
service:
  enabled: true

#======================
# INGRESS
#=====================
ingress: 
  enabled: true
  domain: configserver.argocd

#======================
# CONFIGMAP
#=====================

configmap:
  enabled: false
#   data:
#     server.port: "${PORT_SERVICE}"
#     spring.application.name: "${NAME_SERVICE}"


#======================
# VOLUMES AND MOUNTVOLUMES
#======================

env: 
  enabled: false
  data: {}

#======================
# SECRETS
#======================
secret:
  enabled: true
  portService: ${{secrets.PORT_SERVICE}}
  portTarget: ${{secrets.PORT_TARGET_CONFIGSERVER}}
  DB_HOST: ${{secrets.DB_HOST}}
  DB_USER: ${{secrets.DB_USER}}
  DB_PASS: ${{secrets.DB_PASS}}


extraSecrets:
  enabled: false

#======================
# PVC
#======================
pvc: 
  enabled: false