name: configserver

applabels: configserver
#=====================
# DEPLOYMENT
#=====================

image:
  name: configserver-container
  repository: config-server
  tag: 02

resources:
  enabled: false
  # request:
  #   memory: 64Mi
  #   cpu: 250m
  # limit:
  #   memory: 128Mi
  #   cpu: 500m

#======================
# SERVICE
#=====================
service:
  enabled: true

#======================
# INGRESS
#=====================
ingress: 
  enabled: true
  domain: configserver.ingress

#======================
# CONFIGMAP
#=====================

configmap:
  enabled: false
#   nameConfigMap: orderservice-be-application-propertie-configmap
#   data:
#     server.port: "${PORT_SERVICE}"
#     spring.application.name: "${NAME_SERVICE}"


#======================
# VOLUMES AND MOUNTVOLUMES
#======================



#======================
# SECRETS
#======================
secret:
  enabled: false
  portService: ${{secrets.PORT_SERVICE}}
  portTarget: ${secrets.PORT_TARGET_CONFIGSERVER}}
extraSecrets:
  enabled: false

