name: customerservice

applabels: customerservice
#=====================
# DEPLOYMENT
#=====================

image:
  name: customerservice-container
  repository: customerservice
  tag: "01"

resources:
  enabled: false
  request:
    memory: 64Mi
    cpu: 250m
  limit:
    memory: 128Mi
    cpu: 500m

#======================
# SERVICE
#=====================
service:
  enabled: true

#======================
# INGRESS
#=====================
ingress: 
  enabled: true
  domain: customer.argocd

#======================
# CONFIGMAP
#=====================

# configmap:
#   enabled: false
#   nameConfigMap: orderservice-be-application-propertie-configmap
#   data:
#     server.port: "${PORT_SERVICE}"
#     spring.application.name: "${NAME_SERVICE}"


#======================
# VOLUMES AND MOUNTVOLUMES
#======================



#======================
# SECRETS
#======================
secret:
  enabled: true
  portService: ${{secrets.PORT_SERVICE}}
  portTarget: ${secrets.PORT_TARGET_CUSTOMER}

env:
  enabled: true
  data: 
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: configserver-secret
          key: DB_HOST
          optional: false
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: configserver-secret
          key: DB_USER
          optional: false

    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: configserver-secret
          key: DB_PASS
          optional: false
  
extraSecrets:
  enabled: false
#======================
# PVC
#======================
pvc:
  enabled: false