name: orderservice-be

applabels: orderservice-be
#=====================
# DEPLOYMENT
#=====================

image:
  name: orderservicecontainer
  repository: orderservice
  tag: 62

resources:
  enabled: false
  request:
    memory: 64Mi
    cpu: 250m
  limit:
    memory: 128Mi
    cpu: 500m

#======================
# SERVICE
#=====================
service:
  enabled: false
  name:

#======================
# INGRESS
#=====================
ingress: 
  enabled: false
  domain: order.local

#======================
# CONFIGMAP
#=====================
configmap:
  enabled: false
  nameConfigMap: orderservice-be-application-propertie-configmap
  data:
    server.port: "${PORT_SERVICE}"
    spring.application.name: "${NAME_SERVICE}"


#======================
# VOLUMES AND MOUNTVOLUMES
#======================
volumes:
  - name: application-properties-config-volume
    configMap:
      name: orderservice-be-application-propertie-configmap


volumeMounts:
  - name: application-properties-config-volume
    mountPath: /run/src/main/resources/application.properties
    subPath: application.properties

#======================
# SECRET
#======================
secret:
  enabled: true
  name: 
  
extraSecrets:
  enabled: true
    - name: serviceB-secret
    - name: shared-secret