{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.nameConfigMap }}
  namespace: {{ .Release.Namespace }}
data:
  application.properties: |
    {{- range $key, $value := .Values.config.data }}
    {{ $key }}={{ $value }}
    {{- end }}
{{- end }}
