{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  application.properties: |
{{- with .Values.configmap.data }}
{{- range $key, $value := . }}
    {{ $key }}: "{{ $value }}"
{{- end }}
{{- else }}
    # no configuration data provided
{{- end }}
{{- else }}
# configmap.disabled
{{- end }}
