# ConfigMap for {{ .Values.name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  application.properties: |
{{- range $key, $value := .Values.configmap.data }}
    {{ $key }}={{ $value }}
{{- end }}
{{- if not .Values.configmap.data }}
    # no configuration data provided
{{- end }}