{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{  .Values.name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  application.properties: |
{{- range $key, $value := .Values.configmap.data }}
    {{ $key }}={{ $value | quote }}
{{- end }}
{{- else }}
# ConfigMap disabled
{{- end }}
